// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SimpleBankAPI.Data;

#nullable disable

namespace SimpleBankAPI.Migrations
{
    [DbContext(typeof(AccountContext))]
    partial class AccountContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0-preview.6.23329.4");

            modelBuilder.Entity("SimpleBankAPI.Models.Entities.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Balance")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Accounts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("33983e90-750a-475d-b4f8-e0ff8800c6a5"),
                            Balance = 100m,
                            Name = "Lazy Susan"
                        },
                        new
                        {
                            Id = new Guid("747748e4-2647-4e16-a64c-47745fca51d3"),
                            Balance = 5000m,
                            Name = "John Deere"
                        },
                        new
                        {
                            Id = new Guid("6e3ba52b-dccc-4640-9d70-677f9c6e22ba"),
                            Balance = 25000m,
                            Name = "Mary Poppins"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
